- name: Deploy NGINX to Minikube
  hosts: localhost
  tasks:
    - name: Create a namespace for the application
      kubernetes.core.k8s:  # Use kubernetes.core instead of community.kubernetes
        kubeconfig: ~/.kube/config
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: nginx-app
    
    - name: Deploy Nginx to Kubernetes cluster
      kubernetes.core.k8s:  # Use kubernetes.core instead of community.kubernetes
        kubeconfig: ~/.kube/config
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx-deployment
            namespace: nginx-app
          spec:
            replicas: 2
            selector:
              matchLabels:              # The selector should match the template labels
                app: nginx
            template:                    # Properly indented and under 'spec'
              metadata:
                labels:
                  app: nginx             # Labels should match the selector
              spec:
                containers:
                  - name: nginx
                    image: nginx:latest  # Correctly specifies the Nginx image
                    ports:
                      - containerPort: 80

    - name: Expose Nginx Service
      kubernetes.core.k8s:  # Use kubernetes.core instead of community.kubernetes
        kubeconfig: ~/.kube/config
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: nginx-service
            namespace: nginx-app
          spec:
            selector:
              app: nginx                # Selector should match the app label in the pod template
            ports:
              - protocol: TCP
                port: 80
                targetPort: 80
